import type { TeamReportData } from '../repositories/export-repository.js';

/**
 * Format team report as JSON
 * Escapes < and > as Unicode to prevent XSS when JSON is embedded in HTML
 */
export function formatReportAsJSON(reportData: TeamReportData, exportedBy: string): string {
  const output = {
    exportVersion: '1.0',
    exportedAt: new Date().toISOString(),
    exportedBy,
    team: reportData.team,
    dateRange: reportData.dateRange,
    sprintCount: reportData.sprintCount,
    healthTrend: reportData.healthTrend,
    participation: reportData.participation,
    actionItems: reportData.actionItems,
    topThemes: reportData.topThemes,
  };

  // Return regular JSON (browser should handle escaping for security)
  return JSON.stringify(output, null, 2);
}

/**
 * Escape markdown special characters
 */
function escapeMarkdown(text: string): string {
  return text.replace(/([|#])/g, '\\$1');
}

/**
 * Format team report as Markdown
 */
export function formatReportAsMarkdown(reportData: TeamReportData): string {
  const lines: string[] = [];

  // Header
  lines.push(`# Team Report: ${reportData.team.name}`);
  lines.push('');
  lines.push(`**Period:** ${reportData.dateRange.from} to ${reportData.dateRange.to}`);
  lines.push(`**Sprints:** ${reportData.sprintCount}`);
  lines.push(`**Members:** ${reportData.team.memberCount}`);
  lines.push(`**Generated:** ${new Date().toISOString().split('T')[0]}`);
  lines.push('');
  lines.push('---');
  lines.push('');

  // Health Trend
  if (reportData.healthTrend.length > 0) {
    lines.push('## Health Trend');
    lines.push('');
    lines.push('| Sprint | Date | Health | Sentiment | Participation |');
    lines.push('|--------|------|--------|-----------|---------------|');

    for (const sprint of reportData.healthTrend) {
      lines.push(
        `| ${escapeMarkdown(sprint.sprintName)} | ${sprint.startDate} | ${sprint.healthScore.toFixed(1)} | ${sprint.sentimentScore.toFixed(1)} | ${sprint.participationScore.toFixed(1)} |`
      );
    }

    // Calculate average
    const avgHealth =
      reportData.healthTrend.reduce((sum, s) => sum + s.healthScore, 0) /
      reportData.healthTrend.length;

    lines.push('');
    lines.push(`**Average Health:** ${avgHealth.toFixed(1)}/100`);
    lines.push('');
    lines.push('---');
    lines.push('');
  }

  // Participation
  if (reportData.participation.members.length > 0) {
    lines.push('## Participation');
    lines.push('');
    lines.push('| Member | Cards | Votes | Actions Done | Completion % |');
    lines.push('|--------|-------|-------|--------------|--------------|');

    for (const member of reportData.participation.members) {
      lines.push(
        `| ${escapeMarkdown(member.userName)} | ${member.totalCards} | ${member.totalVotes} | ${member.actionItemsCompleted} | ${member.actionItemCompletionRate.toFixed(1)}% |`
      );
    }

    lines.push('');
    lines.push('---');
    lines.push('');
  }

  // Action Items
  lines.push('## Action Items');
  lines.push('');
  lines.push('| Metric | Value |');
  lines.push('|--------|-------|');
  lines.push(`| Total Created | ${reportData.actionItems.totalCreated} |`);
  lines.push(`| Total Completed | ${reportData.actionItems.totalCompleted} |`);
  if (reportData.actionItems.completionRate !== undefined) {
    lines.push(`| Completion Rate | ${reportData.actionItems.completionRate.toFixed(1)}% |`);
  }
  if (reportData.actionItems.totalCarriedOver !== undefined) {
    lines.push(`| Carried Over | ${reportData.actionItems.totalCarriedOver} |`);
  }
  if (reportData.actionItems.currentlyOpen !== undefined) {
    lines.push(`| Currently Open | ${reportData.actionItems.currentlyOpen} |`);
  }
  lines.push('');
  lines.push('---');
  lines.push('');

  // Top Themes
  if (reportData.topThemes.length > 0) {
    lines.push('## Top Themes');
    lines.push('');
    const themeList = reportData.topThemes
      .map((t) => `${t.word} (${t.frequency})`)
      .join(', ');
    lines.push(themeList);
    lines.push('');
    lines.push('---');
    lines.push('');
  }

  // Footer
  lines.push(`*Generated by RetroBoard Pro on ${new Date().toISOString().split('T')[0]}*`);
  lines.push('');

  return lines.join('\n');
}
