-- Migration: 018_seed_analytics_data
-- Description: Seed sentiment_lexicon and stop_words tables with initial data
-- Created: 2026-02-15

-- Seed sentiment lexicon with representative words covering full sentiment range
INSERT INTO sentiment_lexicon (word, score) VALUES
  -- Strongly positive (+4 to +5)
  ('excellent', 4.5),
  ('outstanding', 4.5),
  ('amazing', 4.0),
  ('fantastic', 4.0),
  ('wonderful', 4.0),
  ('brilliant', 4.0),
  ('superb', 4.0),
  ('exceptional', 4.0),

  -- Positive (+2 to +3.9)
  ('great', 3.0),
  ('awesome', 3.0),
  ('love', 3.0),
  ('perfect', 3.5),
  ('improved', 2.5),
  ('collaboration', 2.0),
  ('helpful', 2.0),
  ('smooth', 2.0),
  ('efficient', 2.5),
  ('productive', 2.5),
  ('successful', 3.0),
  ('progress', 2.0),
  ('reliable', 2.0),
  ('clear', 2.0),
  ('fast', 2.0),
  ('solved', 2.5),
  ('achieved', 2.5),
  ('delivered', 2.0),
  ('teamwork', 2.5),
  ('supportive', 2.5),
  ('effective', 2.5),
  ('completed', 2.0),
  ('streamlined', 2.5),
  ('impressed', 2.5),
  ('appreciated', 2.0),

  -- Mildly positive (+0.5 to +1.9)
  ('good', 1.5),
  ('nice', 1.5),
  ('okay', 0.5),
  ('fine', 1.0),
  ('decent', 1.0),
  ('stable', 1.0),
  ('consistent', 1.0),
  ('adequate', 0.5),
  ('reasonable', 1.0),
  ('functional', 1.0),
  ('workable', 1.0),
  ('acceptable', 1.0),

  -- Neutral (0)
  ('normal', 0.0),
  ('average', 0.0),
  ('usual', 0.0),
  ('standard', 0.0),

  -- Mildly negative (-0.5 to -1.9)
  ('slow', -1.5),
  ('confusing', -1.5),
  ('unclear', -1.5),
  ('difficult', -1.0),
  ('challenging', -0.5),
  ('complex', -0.5),
  ('delayed', -1.5),
  ('missed', -1.5),
  ('lacking', -1.5),
  ('inconsistent', -1.0),
  ('incomplete', -1.0),
  ('rushed', -1.0),
  ('messy', -1.5),
  ('scattered', -1.0),

  -- Negative (-2 to -3.9)
  ('bad', -2.5),
  ('broken', -2.5),
  ('failed', -3.0),
  ('frustrating', -2.5),
  ('blocked', -2.5),
  ('unstable', -2.0),
  ('buggy', -2.5),
  ('crashed', -3.0),
  ('painful', -2.5),
  ('overwhelming', -2.0),
  ('chaotic', -2.5),
  ('disorganized', -2.0),
  ('stressful', -2.5),
  ('terrible', -3.5),
  ('awful', -3.5),
  ('horrible', -3.5),
  ('wasteful', -2.0),
  ('regressed', -2.5),
  ('poor', -2.0),
  ('worse', -2.5),
  ('problematic', -2.0),
  ('regression', -2.5),

  -- Strongly negative (-4 to -5)
  ('catastrophic', -4.5),
  ('disaster', -4.0),
  ('nightmare', -4.0),
  ('unacceptable', -4.0),
  ('impossible', -3.5),
  ('devastating', -4.0),

  -- Retro-specific terms
  ('blocker', -3.0),
  ('improvement', 2.0),
  ('velocity', 1.0),
  ('sprint', 0.5),
  ('retrospective', 0.5),
  ('bottleneck', -2.0),
  ('dependency', -1.5),
  ('technical', -0.5),
  ('refactor', 1.0),
  ('automation', 2.0),
  ('deployment', 1.0),
  ('release', 1.5),
  ('quality', 1.5),
  ('testing', 1.0),
  ('documentation', 0.5),
  ('communication', 1.5),
  ('meeting', -0.5)
ON CONFLICT (word) DO NOTHING;

-- Seed stop words (common English words excluded from analysis)
INSERT INTO stop_words (word) VALUES
  ('the'), ('and'), ('that'), ('this'), ('with'), ('from'),
  ('have'), ('been'), ('were'), ('they'), ('their'), ('what'),
  ('when'), ('would'), ('could'), ('should'), ('about'), ('also'),
  ('some'), ('more'), ('very'), ('just'), ('like'), ('into'),
  ('than'), ('them'), ('then'), ('only'), ('over'), ('such'),
  ('make'), ('made'), ('much'), ('well'), ('back'), ('being'),
  ('many'), ('each'), ('will'), ('does'), ('done'), ('need'),
  ('want'), ('work'), ('think'), ('know'), ('time'), ('really'),
  ('things'), ('going'), ('still'), ('keep'), ('there'), ('here'),
  ('where'), ('which'), ('while'), ('after'), ('before'), ('during'),
  ('between'), ('through'), ('these'), ('those'), ('other'), ('because'),
  ('since'), ('even'), ('same'), ('different'), ('every'), ('most'),
  ('another'), ('around'), ('under'), ('again'), ('never'), ('always'),
  ('often'), ('sometimes'), ('usually'), ('might'), ('however'), ('although'),
  ('though'), ('enough'), ('already'), ('actually'), ('probably'), ('perhaps'),
  ('rather'), ('quite'), ('something'), ('anything'), ('everything'), ('nothing'),
  ('someone'), ('anyone'), ('everyone'), ('able'), ('using'), ('used'),
  ('uses'), ('start'), ('started'), ('stop'), ('stopped'), ('getting'),
  ('doing'), ('having'), ('without'), ('within'), ('against'), ('between'),
  ('until'), ('upon')
ON CONFLICT (word) DO NOTHING;
