export const ErrorCode = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_EMAIL_EXISTS: 'AUTH_EMAIL_EXISTS',
  AUTH_REFRESH_TOKEN_INVALID: 'AUTH_REFRESH_TOKEN_INVALID',
  AUTH_REFRESH_TOKEN_EXPIRED: 'AUTH_REFRESH_TOKEN_EXPIRED',
  FORBIDDEN: 'FORBIDDEN',
  RATE_LIMITED: 'RATE_LIMITED',
  SPRINT_ALREADY_ACTIVE: 'SPRINT_ALREADY_ACTIVE',
  SPRINT_NOT_FOUND: 'SPRINT_NOT_FOUND',
  SPRINT_INVALID_TRANSITION: 'SPRINT_INVALID_TRANSITION',
  SPRINT_NOT_EDITABLE: 'SPRINT_NOT_EDITABLE',
  SPRINT_DATE_INVALID: 'SPRINT_DATE_INVALID',
  TEMPLATE_NOT_FOUND: 'TEMPLATE_NOT_FOUND',
  TEAM_INVITE_EXHAUSTED: 'TEAM_INVITE_EXHAUSTED',
  TEAM_NOT_FOUND: 'TEAM_NOT_FOUND',
  TEAM_NOT_MEMBER: 'TEAM_NOT_MEMBER',
  TEAM_INSUFFICIENT_ROLE: 'TEAM_INSUFFICIENT_ROLE',
  BOARD_NOT_FOUND: 'BOARD_NOT_FOUND',
  BOARD_ALREADY_EXISTS: 'BOARD_ALREADY_EXISTS',
  CARD_NOT_FOUND: 'CARD_NOT_FOUND',
  GROUP_NOT_FOUND: 'GROUP_NOT_FOUND',
  INVALID_PHASE: 'INVALID_PHASE',
  VOTE_LIMIT_REACHED: 'VOTE_LIMIT_REACHED',
  INVALID_DURATION: 'INVALID_DURATION',
  TIMER_CONFLICT: 'TIMER_CONFLICT',
  TIMER_NOT_RUNNING: 'TIMER_NOT_RUNNING',
  TIMER_NOT_PAUSED: 'TIMER_NOT_PAUSED',
  TIMER_NOT_FOUND: 'TIMER_NOT_FOUND',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  INVALID_EMOJI: 'INVALID_EMOJI',
  BOARD_LOCKED: 'BOARD_LOCKED',
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];

export class AppError extends Error {
  constructor(
    public readonly code: ErrorCodeType,
    public readonly status: number,
    message: string,
  ) {
    super(message);
    this.name = 'AppError';
  }
}

export function formatErrorResponse(code: string, message: string) {
  return {
    error: {
      code,
      message,
    },
  };
}
